version: '3.8'

services:  
  nodejs-app:
    build:
      context: ./nodejs-app 
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - "8080:8080"
    volumes:
        - ./nodejs-logs:/src/logs

volumes:
    elasticsearch_data:
        driver: local
